development:
  password: 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
  theme_id: "126747050179"
  store: https://gryning.myshopify.com
production:
  password: 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
  theme_id: "126746984643"
  store: https://gryning.myshopify.com
  timeout: 60s
  readonly: true
